version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - htmlzip
  - pdf
  - epub

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"