[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "identitwin"
version = "0.0.1"
authors = [
    { name = "Ing. Angel Navarro-Mora M.Sc", email = "ahnavarro@itcr.ac.cr, ahnavarro@anmingenieria.com" },
    { name = "Alvaro Perez-Mora", email = "alvaroenrique2001@estudiantec.cr" },
]

readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
  "Programming Language :: Python :: 3.12",
  "License :: OSI Approved :: MIT License",
]
dependencies = []
[project.urls]
"Homepage" = "https://github.com/estructuraPy/IdentiTwin"

[tool.setuptools]
packages = ["identitwin"]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
identitwin = ["tests/*.py"]